"""Models package for AI Research Assistant."""

from backend.app.models.evidence import (
    PaperRecord,
    EvidenceRecord,
    EvidenceSpan,
    Claim,
    PaperSection,
    ProvenanceInfo,
    ReviewClaim,
    PRISMATracker,
    SearchProtocol,
    TaxonomyTheme,
    ValidationReport,
    ConfidenceBasis,
    make_paper_id,
    make_evidence_id,
    make_claim_id,
    make_span_id,
    score_confidence,
    confidence_label,
    locate_quote,
    resolve_record_chain,
    apply_chain_downgrade,
    build_evidence_chains,
    build_claims,
)

__all__ = [
    "PaperRecord",
    "EvidenceRecord",
    "EvidenceSpan",
    "Claim",
    "PaperSection",
    "ProvenanceInfo",
    "ReviewClaim",
    "PRISMATracker",
    "SearchProtocol",
    "TaxonomyTheme",
    "ValidationReport",
    "ConfidenceBasis",
    "make_paper_id",
    "make_evidence_id",
    "make_claim_id",
    "make_span_id",
    "score_confidence",
    "confidence_label",
    "locate_quote",
    "resolve_record_chain",
    "apply_chain_downgrade",
    "build_evidence_chains",
    "build_claims",
]
